"""Routes for /api/invoices — supports both invoices AND quotations.

Every invoice/quotation's totals are always recomputed server-side from the
items list. Client-sent totals are never trusted.

Document types:
  - document_type='invoice'   — standard sales invoice (has payments)
  - document_type='quotation' — pre-sale quote (no payments, no inventory)

Numbering (auto-generated by the server, never client-supplied):
  Invoices:   INV-YYYY-MM-DD:NNNN  (e.g., INV-2026-10-03:0001)
  Quotations: QTN-YYYY-MM-DD:NNNN  (e.g., QTN-2026-10-03:0001)
  Counter resets daily. Same-day duplicates are handled via retry.

Payment tracking: only allowed on document_type='invoice'.
Inventory: decremented only on document_type='invoice'.

Audit trail: same rules as before — one row per changed field on PUT.
"""

from __future__ import annotations

from datetime import date
from decimal import ROUND_HALF_UP, Decimal, InvalidOperation

from flask import Blueprint, request
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError, SQLAlchemyError

from extensions import db
from models import Client, Inventory, Invoice, InvoiceAudit, InvoiceItem, InvoicePayment
from utils.responses import api_response

invoices_bp = Blueprint("invoices", __name__)
payments_bp = Blueprint("payments", __name__)

ALLOWED_DOCUMENT_TYPES = {"invoice", "quotation"}
INVOICE_STATUSES = {"Draft", "Sent", "Paid", "Overdue"}
QUOTATION_STATUSES = {"Draft", "Sent", "Accepted", "Rejected"}
ALLOWED_PAYMENT_METHODS = {"cash", "bank_transfer", "card", "cheque", "other"}
TOP_LEVEL_EDITABLE_FIELDS = {
    "client_id", "lpo_number", "issued", "due", "valid_until",
    "status", "vat_percent", "notes", "items",
}
AUDITED_SCALAR_FIELDS = (
    "client_id", "lpo_number", "invoice_number", "issued", "due",
    "valid_until", "status", "vat_percent", "notes", "subtotal", "vat", "total",
)
TWO_DP = Decimal("0.01")
HUNDRED = Decimal("100")


# --- small helpers -----------------------------------------------------


def _to_decimal(value, field_name: str) -> Decimal:
    try:
        return Decimal(str(value))
    except (InvalidOperation, TypeError):
        raise ValueError(f"'{field_name}': '{value}' is not a valid number.")


def _quantize(value: Decimal) -> Decimal:
    return value.quantize(TWO_DP, rounding=ROUND_HALF_UP)


def _parse_date(value, field_name: str) -> date | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise ValueError(f"'{field_name}' must be an ISO date string ('YYYY-MM-DD').")
    try:
        return date.fromisoformat(value)
    except ValueError:
        raise ValueError(f"'{field_name}': '{value}' is not a valid ISO date ('YYYY-MM-DD').")


def _audit_str(value) -> str | None:
    return None if value is None else str(value)


def _allowed_statuses(document_type: str) -> set[str]:
    """Return the valid status set for this document type."""
    return INVOICE_STATUSES if document_type == "invoice" else QUOTATION_STATUSES


def _generate_document_number(document_type: str, issued_date: date | None = None) -> str:
    """Generate the next invoice/quotation number in YYYY-MM-DD:NNNN format.

    Daily reset. Prefixes: INV- for invoices, QTN- for quotations.

    Retries up to 20 times if a race condition creates a duplicate.

    Args:
        document_type: 'invoice' or 'quotation'.
        issued_date: The issued date to use (defaults to today).

    Returns:
        A unique document number like 'INV-2026-10-03:0001'.
    """
    prefix = "INV" if document_type == "invoice" else "QTN"
    d = issued_date or date.today()
    date_part = d.strftime("%Y-%m-%d")
    pattern = f"{prefix}-{date_part}:%"

    for attempt in range(20):
        # Find the highest sequence number for today
        last = (
            Invoice.query
            .filter(Invoice.invoice_number.like(pattern))
            .order_by(Invoice.invoice_number.desc())
            .first()
        )
        if last is None:
            seq = 1
        else:
            try:
                seq = int(last.invoice_number.split(":")[-1]) + 1
            except (ValueError, IndexError):
                seq = 1

        candidate = f"{prefix}-{date_part}:{seq:04d}"
        # Check for collision (shouldn't happen but race conditions possible)
        if Invoice.query.filter_by(invoice_number=candidate).first() is None:
            return candidate
        # Collision — retry with next sequence
    # Fallback: append a random suffix if 20 retries all fail
    import uuid
    return f"{prefix}-{date_part}:{uuid.uuid4().hex[:6]}"


def _items_signature(items) -> list[dict]:
    """Comparable snapshot of an item list for audit diffing."""
    out = []
    for i in items:
        if hasattr(i, "product_name"):
            out.append({
                "product_name": i.product_name,
                "brand": i.brand,
                "unit_price": str(i.unit_price),
                "qty": str(i.qty),
                "foc_qty": str(i.foc_qty),
                "discount_percent": str(i.discount_percent),
                "discount_amount": str(i.discount_amount),
                "amount": str(i.amount),
                "vat_percent": str(i.vat_percent),
                "vat_amount": str(i.vat_amount),
            })
        else:
            out.append({
                "product_name": i.get("product_name"),
                "brand": i.get("brand"),
                "unit_price": str(i.get("unit_price")),
                "qty": str(i.get("qty")),
                "foc_qty": str(i.get("foc_qty")),
                "discount_percent": str(i.get("discount_percent")),
                "discount_amount": str(i.get("discount_amount")),
                "amount": str(i.get("amount")),
                "vat_percent": str(i.get("vat_percent")),
                "vat_amount": str(i.get("vat_amount")),
            })
    return out


def _validate_items_payload(raw_items) -> tuple[list[dict] | None, str | None]:
    """Validate + clean nested items.

    Returns (cleaned_items, None) on success or (None, error_message).
    """
    if not isinstance(raw_items, list) or len(raw_items) == 0:
        return None, "'items' must be a non-empty list."

    cleaned = []
    for idx, raw in enumerate(raw_items):
        if not isinstance(raw, dict):
            return None, f"items[{idx}] must be an object."

        product_name = raw.get("product_name")
        if not isinstance(product_name, str) or not product_name.strip():
            return None, f"items[{idx}].product_name is required and must be a non-empty string."

        brand = raw.get("brand")
        if brand is not None and not isinstance(brand, str):
            return None, f"items[{idx}].brand must be a string."

        if "unit_price" not in raw:
            return None, f"items[{idx}].unit_price is required."
        try:
            unit_price = _to_decimal(raw["unit_price"], f"items[{idx}].unit_price")
        except ValueError as exc:
            return None, str(exc)
        if unit_price < 0:
            return None, f"items[{idx}].unit_price must be >= 0."

        if "qty" not in raw:
            return None, f"items[{idx}].qty is required."
        try:
            qty = _to_decimal(raw["qty"], f"items[{idx}].qty")
        except ValueError as exc:
            return None, str(exc)
        if qty <= 0:
            return None, f"items[{idx}].qty must be > 0."

        try:
            foc_qty = _to_decimal(raw.get("foc_qty", 0), f"items[{idx}].foc_qty")
        except ValueError as exc:
            return None, str(exc)
        if foc_qty < 0:
            return None, f"items[{idx}].foc_qty must be >= 0."

        try:
            discount_percent = _to_decimal(raw.get("discount_percent", 0), f"items[{idx}].discount_percent")
        except ValueError as exc:
            return None, str(exc)
        if not (Decimal("0") <= discount_percent <= HUNDRED):
            return None, f"items[{idx}].discount_percent must be between 0 and 100."

        try:
            vat_percent = _to_decimal(raw.get("vat_percent", 0), f"items[{idx}].vat_percent")
        except ValueError as exc:
            return None, str(exc)
        if not (Decimal("0") <= vat_percent <= HUNDRED):
            return None, f"items[{idx}].vat_percent must be between 0 and 100."

        cleaned.append({
            "product_name": product_name.strip(),
            "brand": brand,
            "unit_price": unit_price,
            "qty": qty,
            "foc_qty": foc_qty,
            "discount_percent": discount_percent,
            "vat_percent": vat_percent,
        })

    return cleaned, None


def _compute_line_amounts(item: dict) -> dict:
    """Given a cleaned item dict, return the fully-calculated amounts."""
    unit_price = item["unit_price"]
    qty = item["qty"]
    discount_percent = item["discount_percent"]
    vat_percent = item["vat_percent"]

    amount = _quantize(unit_price * qty)
    discount_amount = _quantize(amount * discount_percent / HUNDRED)
    taxable = amount - discount_amount
    vat_amount = _quantize(taxable * vat_percent / HUNDRED)

    out = dict(item)
    out["amount"] = amount
    out["discount_amount"] = discount_amount
    out["vat_amount"] = vat_amount
    return out


def _compute_invoice_totals(items_with_amounts: list[dict]) -> tuple[Decimal, Decimal, Decimal]:
    """Return (subtotal, total_discount, total_vat) from fully-calculated items."""
    subtotal = Decimal("0")
    total_discount = Decimal("0")
    total_vat = Decimal("0")
    for item in items_with_amounts:
        subtotal += item["amount"]
        total_discount += item["discount_amount"]
        total_vat += item["vat_amount"]
    return _quantize(subtotal), _quantize(total_discount), _quantize(total_vat)


def _build_invoice_item(calc_item: dict) -> InvoiceItem:
    """Build an InvoiceItem ORM object from a fully-calculated item dict."""
    return InvoiceItem(
        product_name=calc_item["product_name"],
        brand=calc_item["brand"],
        unit_price=calc_item["unit_price"],
        qty=calc_item["qty"],
        foc_qty=calc_item["foc_qty"],
        discount_percent=calc_item["discount_percent"],
        discount_amount=calc_item["discount_amount"],
        amount=calc_item["amount"],
        vat_percent=calc_item["vat_percent"],
        vat_amount=calc_item["vat_amount"],
    )


def _decrement_inventory(cleaned_items: list[dict]) -> None:
    """Best-effort stock decrement, matched by case-insensitive product name.
    Uses only PAID qty (foc_qty does NOT decrement inventory)."""
    for item in cleaned_items:
        match = Inventory.query.filter(
            func.lower(Inventory.product) == item["product_name"].lower()
        ).first()
        if match is None:
            continue
        new_balance = match.balance - item["qty"]
        match.balance = new_balance if new_balance > 0 else Decimal("0")


# --- routes --------------------------------------------------------------


@invoices_bp.route("", methods=["GET"])
def list_invoices():
    """GET /api/invoices — list all.

    Query params:
        status — filter by status (validation depends on document_type)
        type   — filter by document_type ('invoice' or 'quotation')
    """
    query = Invoice.query

    type_filter = request.args.get("type")
    if type_filter:
        if type_filter not in ALLOWED_DOCUMENT_TYPES:
            return api_response(
                error="invalid_type", message=f"'type' must be one of {sorted(ALLOWED_DOCUMENT_TYPES)}."
            ), 400
        query = query.filter(Invoice.document_type == type_filter)

    status_filter = request.args.get("status")
    if status_filter:
        # Valid statuses depend on document_type — but we accept any known status
        all_statuses = INVOICE_STATUSES | QUOTATION_STATUSES
        if status_filter not in all_statuses:
            return api_response(
                error="invalid_type", message=f"'status' must be one of {sorted(all_statuses)}."
            ), 400
        query = query.filter(Invoice.status == status_filter)

    invoices = query.order_by(Invoice.created_at.desc()).all()
    return api_response(data=[inv.to_dict() for inv in invoices]), 200


@invoices_bp.route("", methods=["POST"])
def create_invoice():
    """POST /api/invoices — create an invoice OR quotation.

    The document_type field is required. Numbering is auto-generated by the
    server (YYYY-MM-DD:NNNN format, daily reset, INV-/QTN- prefixes).
    """
    body = request.get_json(silent=True)
    if body is None or not isinstance(body, dict):
        return api_response(error="invalid_json", message="Request body must be a JSON object."), 400

    # Document type is required and controls everything else
    document_type = body.get("document_type")
    if document_type not in ALLOWED_DOCUMENT_TYPES:
        return api_response(
            error="missing_field",
            message=f"'document_type' is required and must be one of {sorted(ALLOWED_DOCUMENT_TYPES)}.",
        ), 400

    unknown = set(body.keys()) - TOP_LEVEL_EDITABLE_FIELDS - {"document_type"}
    if unknown:
        return api_response(
            error="unknown_fields", message=f"Unrecognized field(s): {', '.join(sorted(unknown))}."
        ), 400

    client_id = body.get("client_id")
    if not isinstance(client_id, int):
        return api_response(error="missing_field", message="'client_id' is required and must be an integer."), 400

    status = body.get("status", "Draft")
    if status not in _allowed_statuses(document_type):
        return api_response(
            error="invalid_type",
            message=f"'status' for a {document_type} must be one of {sorted(_allowed_statuses(document_type))}.",
        ), 400

    try:
        vat_percent = _to_decimal(body.get("vat_percent", 0), "vat_percent")
    except ValueError as exc:
        return api_response(error="invalid_type", message=str(exc)), 400
    if not (Decimal("0") <= vat_percent <= HUNDRED):
        return api_response(error="invalid_type", message="'vat_percent' must be between 0 and 100."), 400

    try:
        issued = _parse_date(body.get("issued"), "issued")
        due = _parse_date(body.get("due"), "due")
        valid_until = _parse_date(body.get("valid_until"), "valid_until")
    except ValueError as exc:
        return api_response(error="invalid_type", message=str(exc)), 400

    lpo_number = body.get("lpo_number")
    if lpo_number is not None and not isinstance(lpo_number, str):
        return api_response(error="invalid_type", message="'lpo_number' must be a string."), 400

    notes = body.get("notes")
    if notes is not None and not isinstance(notes, str):
        return api_response(error="invalid_type", message="'notes' must be a string."), 400

    cleaned_items, err = _validate_items_payload(body.get("items"))
    if err:
        return api_response(error="invalid_type", message=err), 400

    if Client.query.get(client_id) is None:
        return api_response(
            error="fk_conflict", message=f"No client with id {client_id}. Create the client first."
        ), 409

    # Auto-generate document number based on issued date
    invoice_number = _generate_document_number(document_type, issued)

    calc_items = [_compute_line_amounts(i) for i in cleaned_items]
    subtotal, total_discount, total_vat = _compute_invoice_totals(calc_items)
    total = _quantize(subtotal - total_discount + total_vat)

    invoice = Invoice(
        document_type=document_type,
        client_id=client_id, lpo_number=lpo_number, invoice_number=invoice_number,
        issued=issued, due=due, valid_until=valid_until, status=status,
        vat_percent=vat_percent, notes=notes,
        subtotal=subtotal, vat=total_vat, total=total,
    )
    for calc_item in calc_items:
        invoice.items.append(_build_invoice_item(calc_item))

    db.session.add(invoice)
    db.session.flush()

    db.session.add(InvoiceAudit(
        invoice_id=invoice.id, action="create", field_name=None, old_value=None,
        new_value=f"{document_type}={invoice_number}, total={total}",
    ))

    # Only decrement inventory for actual invoices, not quotations
    if document_type == "invoice":
        _decrement_inventory(cleaned_items)

    try:
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        return api_response(
            error="conflict",
            message=f"Document number '{invoice_number}' already exists (race with another request).",
        ), 409
    except SQLAlchemyError as exc:
        db.session.rollback()
        return api_response(error="db_error", message=str(exc)), 500

    return api_response(data=invoice.to_dict()), 201


@invoices_bp.route("/<int:invoice_id>", methods=["GET"])
def get_invoice(invoice_id: int):
    invoice = Invoice.query.get(invoice_id)
    if invoice is None:
        return api_response(error="not_found", message=f"No document with id {invoice_id}."), 404
    return api_response(data=invoice.to_dict()), 200


@invoices_bp.route("/<int:invoice_id>", methods=["PUT"])
def update_invoice(invoice_id: int):
    """PUT /api/invoices/<id> — update fields. Does NOT allow changing document_type."""
    invoice = Invoice.query.get(invoice_id)
    if invoice is None:
        return api_response(error="not_found", message=f"No document with id {invoice_id}."), 404

    body = request.get_json(silent=True)
    if body is None or not isinstance(body, dict):
        return api_response(error="invalid_json", message="Request body must be a JSON object."), 400

    # document_type and invoice_number cannot be changed after creation
    if "document_type" in body:
        return api_response(error="invalid_field", message="'document_type' cannot be changed after creation."), 400
    if "invoice_number" in body:
        return api_response(error="invalid_field", message="'invoice_number' cannot be changed after creation."), 400

    unknown = set(body.keys()) - TOP_LEVEL_EDITABLE_FIELDS
    if unknown:
        return api_response(
            error="unknown_fields", message=f"Unrecognized field(s): {', '.join(sorted(unknown))}."
        ), 400

    new_client_id = invoice.client_id
    if "client_id" in body:
        if not isinstance(body["client_id"], int):
            return api_response(error="invalid_type", message="'client_id' must be an integer."), 400
        if Client.query.get(body["client_id"]) is None:
            return api_response(error="fk_conflict", message=f"No client with id {body['client_id']}."), 409
        new_client_id = body["client_id"]

    new_status = invoice.status
    if "status" in body:
        if body["status"] not in _allowed_statuses(invoice.document_type):
            return api_response(
                error="invalid_type",
                message=f"'status' for a {invoice.document_type} must be one of "
                        f"{sorted(_allowed_statuses(invoice.document_type))}.",
            ), 400
        new_status = body["status"]

    new_vat_percent = invoice.vat_percent
    if "vat_percent" in body:
        try:
            new_vat_percent = _to_decimal(body["vat_percent"], "vat_percent")
        except ValueError as exc:
            return api_response(error="invalid_type", message=str(exc)), 400
        if not (Decimal("0") <= new_vat_percent <= HUNDRED):
            return api_response(error="invalid_type", message="'vat_percent' must be between 0 and 100."), 400

    try:
        new_issued = _parse_date(body["issued"], "issued") if "issued" in body else invoice.issued
        new_due = _parse_date(body["due"], "due") if "due" in body else invoice.due
        new_valid_until = _parse_date(body["valid_until"], "valid_until") if "valid_until" in body else invoice.valid_until
    except ValueError as exc:
        return api_response(error="invalid_type", message=str(exc)), 400

    new_lpo_number = invoice.lpo_number
    if "lpo_number" in body:
        if body["lpo_number"] is not None and not isinstance(body["lpo_number"], str):
            return api_response(error="invalid_type", message="'lpo_number' must be a string."), 400
        new_lpo_number = body["lpo_number"]

    new_notes = invoice.notes
    if "notes" in body:
        if body["notes"] is not None and not isinstance(body["notes"], str):
            return api_response(error="invalid_type", message="'notes' must be a string."), 400
        new_notes = body["notes"]

    old_items_snapshot = _items_signature(invoice.items)
    new_cleaned_items = None
    new_signature = None
    if "items" in body:
        new_cleaned_items, err = _validate_items_payload(body["items"])
        if err:
            return api_response(error="invalid_type", message=err), 400
        new_signature = _items_signature(new_cleaned_items)

    before = {field: getattr(invoice, field) for field in AUDITED_SCALAR_FIELDS}

    invoice.client_id = new_client_id
    invoice.status = new_status
    invoice.vat_percent = new_vat_percent
    invoice.issued = new_issued
    invoice.due = new_due
    invoice.valid_until = new_valid_until
    invoice.lpo_number = new_lpo_number
    invoice.notes = new_notes

    items_changed = False
    if new_cleaned_items is not None:
        items_changed = new_signature != old_items_snapshot
        if items_changed:
            invoice.items.clear()
            for cleaned in new_cleaned_items:
                calc = _compute_line_amounts(cleaned)
                invoice.items.append(_build_invoice_item(calc))

    calc_items_for_totals = [
        {
            "amount": i.amount,
            "discount_amount": i.discount_amount,
            "vat_amount": i.vat_amount,
        } for i in invoice.items
    ]
    subtotal, total_discount, total_vat = _compute_invoice_totals(calc_items_for_totals)
    invoice.subtotal = subtotal
    invoice.vat = total_vat
    invoice.total = _quantize(subtotal - total_discount + total_vat)

    after = {field: getattr(invoice, field) for field in AUDITED_SCALAR_FIELDS}
    for field in AUDITED_SCALAR_FIELDS:
        if before[field] != after[field]:
            action = "status_change" if field == "status" else "update"
            db.session.add(InvoiceAudit(
                invoice_id=invoice.id, action=action, field_name=field,
                old_value=_audit_str(before[field]), new_value=_audit_str(after[field]),
            ))
    if items_changed:
        db.session.add(InvoiceAudit(
            invoice_id=invoice.id, action="update", field_name="items",
            old_value=str(old_items_snapshot), new_value=str(new_signature),
        ))

    try:
        db.session.commit()
    except SQLAlchemyError as exc:
        db.session.rollback()
        return api_response(error="db_error", message=str(exc)), 500

    return api_response(data=invoice.to_dict()), 200


@invoices_bp.route("/<int:invoice_id>", methods=["DELETE"])
def delete_invoice(invoice_id: int):
    invoice = Invoice.query.get(invoice_id)
    if invoice is None:
        return api_response(error="not_found", message=f"No document with id {invoice_id}."), 404

    db.session.add(InvoiceAudit(
        invoice_id=invoice.id, action="delete", field_name=None,
        old_value=f"document_type={invoice.document_type}, invoice_number={invoice.invoice_number}, total={invoice.total}",
        new_value=None,
    ))
    db.session.delete(invoice)

    try:
        db.session.commit()
    except SQLAlchemyError as exc:
        db.session.rollback()
        return api_response(error="db_error", message=str(exc)), 500

    return api_response(data={"id": invoice_id, "deleted": True}), 200


@invoices_bp.route("/<int:invoice_id>/pdf", methods=["GET"])
def invoice_pdf(invoice_id: int):
    return api_response(error="not_implemented", message="PDF generation lands in Stage 4."), 501


@invoices_bp.route("/<int:invoice_id>/convert-to-invoice", methods=["POST"])
def convert_to_invoice(invoice_id: int):
    """POST /api/invoices/<id>/convert-to-invoice — convert a quotation to an invoice.

    Rules:
      - Only quotations can be converted (400 if already an invoice).
      - Creates a NEW invoice row with document_type='invoice', keeping all
        items, client, subtotal, vat, total from the quotation.
      - Auto-generates a new INV-YYYY-MM-DD:NNNN number.
      - Decrements inventory for the new invoice (since it's now a sale).
      - Marks the original quotation's status as 'Accepted'.
      - Returns the new invoice.
    """
    quotation = Invoice.query.get(invoice_id)
    if quotation is None:
        return api_response(error="not_found", message=f"No document with id {invoice_id}."), 404

    if quotation.document_type != "quotation":
        return api_response(
            error="invalid_type", message="Only quotations can be converted to invoices."
        ), 400

    # Mark original as accepted
    quotation.status = "Accepted"

    # Create new invoice with same data
    today = date.today()
    new_number = _generate_document_number("invoice", today)

    new_invoice = Invoice(
        document_type="invoice",
        client_id=quotation.client_id,
        lpo_number=quotation.lpo_number,
        invoice_number=new_number,
        issued=today,
        due=quotation.due,
        status="Draft",
        vat_percent=quotation.vat_percent,
        notes=quotation.notes,
        subtotal=quotation.subtotal,
        vat=quotation.vat,
        total=quotation.total,
    )
    for item in quotation.items:
        new_invoice.items.append(InvoiceItem(
            product_name=item.product_name,
            brand=item.brand,
            unit_price=item.unit_price,
            qty=item.qty,
            foc_qty=item.foc_qty,
            discount_percent=item.discount_percent,
            discount_amount=item.discount_amount,
            amount=item.amount,
            vat_percent=item.vat_percent,
            vat_amount=item.vat_amount,
        ))

    db.session.add(new_invoice)
    db.session.flush()

    # Decrement inventory for the new invoice (it's a sale now)
    for item in quotation.items:
        match = Inventory.query.filter(
            func.lower(Inventory.product) == item.product_name.lower()
        ).first()
        if match is not None:
            new_balance = match.balance - item.qty
            match.balance = new_balance if new_balance > 0 else Decimal("0")

    db.session.add(InvoiceAudit(
        invoice_id=new_invoice.id, action="create", field_name=None, old_value=None,
        new_value=f"converted_from_quotation_id={quotation.id}, invoice_number={new_number}",
    ))
    db.session.add(InvoiceAudit(
        invoice_id=quotation.id, action="status_change", field_name="status",
        old_value="Draft", new_value="Accepted",
    ))

    try:
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        return api_response(
            error="conflict", message=f"Invoice number '{new_number}' already exists (race)."
        ), 409
    except SQLAlchemyError as exc:
        db.session.rollback()
        return api_response(error="db_error", message=str(exc)), 500

    return api_response(data={
        "new_invoice": new_invoice.to_dict(),
        "quotation_id": quotation.id,
    }), 201


# --- payments (only allowed on document_type='invoice') ------------------


@invoices_bp.route("/<int:invoice_id>/payments", methods=["POST"])
def add_payment(invoice_id: int):
    invoice = Invoice.query.get(invoice_id)
    if invoice is None:
        return api_response(error="not_found", message=f"No document with id {invoice_id}."), 404

    if invoice.document_type != "invoice":
        return api_response(
            error="invalid_type", message="Cannot record payments on a quotation. Convert to invoice first."
        ), 400

    body = request.get_json(silent=True)
    if body is None or not isinstance(body, dict):
        return api_response(error="invalid_json", message="Request body must be a JSON object."), 400

    unknown = set(body.keys()) - {"amount", "paid_date", "payment_method", "reference", "notes"}
    if unknown:
        return api_response(
            error="unknown_fields", message=f"Unrecognized field(s): {', '.join(sorted(unknown))}."
        ), 400

    if "amount" not in body:
        return api_response(error="missing_field", message="'amount' is required."), 400
    try:
        amount = _to_decimal(body["amount"], "amount")
    except ValueError as exc:
        return api_response(error="invalid_type", message=str(exc)), 400
    if amount <= 0:
        return api_response(error="invalid_type", message="'amount' must be greater than 0."), 400
    amount = _quantize(amount)

    raw_paid_date = body.get("paid_date")
    if raw_paid_date is None:
        return api_response(error="missing_field", message="'paid_date' is required."), 400
    try:
        paid_date = _parse_date(raw_paid_date, "paid_date")
    except ValueError as exc:
        return api_response(error="invalid_type", message=str(exc)), 400

    payment_method = body.get("payment_method")
    if payment_method is not None and payment_method not in ALLOWED_PAYMENT_METHODS:
        return api_response(
            error="invalid_type",
            message=f"'payment_method' must be one of {sorted(ALLOWED_PAYMENT_METHODS)} or null.",
        ), 400

    reference = body.get("reference")
    if reference is not None and not isinstance(reference, str):
        return api_response(error="invalid_type", message="'reference' must be a string."), 400

    notes = body.get("notes")
    if notes is not None and not isinstance(notes, str):
        return api_response(error="invalid_type", message="'notes' must be a string."), 400

    current_balance = _quantize((invoice.total or Decimal("0")) - (invoice.amount_paid or Decimal("0")))
    if amount > current_balance:
        return api_response(
            error="overpayment",
            message=f"Payment of {amount} exceeds the remaining balance of {current_balance}.",
        ), 409

    payment = InvoicePayment(
        invoice_id=invoice.id, amount=amount, paid_date=paid_date,
        payment_method=payment_method, reference=reference, notes=notes,
    )
    db.session.add(payment)

    old_amount_paid = invoice.amount_paid
    invoice.amount_paid = _quantize((invoice.amount_paid or Decimal("0")) + amount)
    new_balance = _quantize((invoice.total or Decimal("0")) - invoice.amount_paid)
    if new_balance <= 0:
        invoice.status = "Paid"

    db.session.add(InvoiceAudit(
        invoice_id=invoice.id, action="update", field_name="amount_paid",
        old_value=_audit_str(old_amount_paid), new_value=_audit_str(invoice.amount_paid),
    ))

    try:
        db.session.commit()
    except SQLAlchemyError as exc:
        db.session.rollback()
        return api_response(error="db_error", message=str(exc)), 500

    return api_response(data={"payment": payment.to_dict(), "invoice": invoice.to_dict()}), 201


@invoices_bp.route("/<int:invoice_id>/payments", methods=["GET"])
def list_payments(invoice_id: int):
    invoice = Invoice.query.get(invoice_id)
    if invoice is None:
        return api_response(error="not_found", message=f"No document with id {invoice_id}."), 404

    payments = (
        InvoicePayment.query.filter_by(invoice_id=invoice_id)
        .order_by(InvoicePayment.paid_date.desc())
        .all()
    )
    return api_response(data=[p.to_dict() for p in payments]), 200


@payments_bp.route("/payments/<int:payment_id>", methods=["DELETE"])
def delete_payment(payment_id: int):
    payment = InvoicePayment.query.get(payment_id)
    if payment is None:
        return api_response(error="not_found", message=f"No payment with id {payment_id}."), 404

    invoice = payment.invoice

    old_amount_paid = invoice.amount_paid
    new_amount_paid = _quantize((invoice.amount_paid or Decimal("0")) - payment.amount)
    invoice.amount_paid = new_amount_paid if new_amount_paid > 0 else Decimal("0.00")

    new_balance = _quantize((invoice.total or Decimal("0")) - invoice.amount_paid)
    if invoice.status == "Paid" and new_balance > 0:
        invoice.status = "Sent"

    db.session.add(InvoiceAudit(
        invoice_id=invoice.id, action="delete", field_name="amount_paid",
        old_value=_audit_str(old_amount_paid), new_value=_audit_str(invoice.amount_paid),
    ))
    db.session.delete(payment)

    try:
        db.session.commit()
    except SQLAlchemyError as exc:
        db.session.rollback()
        return api_response(error="db_error", message=str(exc)), 500

    return api_response(data={"id": payment_id, "deleted": True}), 200